Productivity.ToDo/Productivity.ToDo.UI/Models/ErrorViewModel.cs
using System;

namespace Productivity.ToDo.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Productivity.ToDo/Productivity.ToDo.UI/Controllers/CompositionDemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Productivity.ToDo.UI.Controllers
{
    public class CompositionDemoController : Controller
    {
        public IActionResult Index()
        {

            // No code in these controllers - we use composition

            return View();
        }
    }
}

Productivity.ToDo/Productivity.ToDo.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Productivity.ToDo.UI.Models;

namespace Productivity.ToDo.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Productivity.ToDo/Productivity.ToDo.UI/Views/CompositionDemo/Index.cshtml
@{
    ViewData["Title"] = "ToDo";
}
<div class="row">
    <div class="col-md-6">
        <div class="todolist not-done">
            <h1>Todos</h1>
            <hr>
            <ul id="tasks" class="list-unstyled">
                @foreach (dynamic t in Model.ToDos)
                {
                    <li class="ui-state-default" id="@t.Id">
                        <div class="checkbox">
                            <label class="text-value">
                              <span class="inner-text">@t.Text (@t.Info)</span>
                            </label>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

Productivity.ToDo/Productivity.ToDo.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "ToDo";
}

<div class="row">
    <div class="col-md-6">
        <div class="todolist not-done">
            <h1>Todos</h1>
            <input type="text" class="form-control add-todo" placeholder="Add todo">

            <hr>
            <ul id="tasks" class="list-unstyled">
              
            </ul>
            <hr>
            <div class="todo-footer">
                <button id="checkAll" class="btn btn-success"><span class="glyphicon glyphicon-check"></span>&nbsp;Mark all as complete</button>
                <button id="deleteAll" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span>&nbsp;Delete all</button>
            </div>
        </div>
    </div>
</div>



@section scripts{

    <!-- Template -->
    <script id="hidden-template" type="text/x-custom-template">
        <li class="ui-state-default" id="template">
            <div class="checkbox">
                <label class="text-value">
                    <input type="checkbox" value="" /><span class="inner-text"></span>
                </label>
                <button class="remove-item btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-trash"></span></button>
            </div>

        </li>
    </script>

    <script>

        $(document).ready(function () {

            var template = $('#hidden-template').html();

            $.ajax({

                url: 'https://localhost:44334/api/v1.0/ToDoItems',
                dataType: "json",
                type: "GET",
                success: function (data) {

                    $.each(data, function (index, value) {

                        //Clone the template
                        var item = $(template).clone();

                        $(item).attr("id", value.id);

                        var displayText = value.text;

                        if (value.info != null) {
                            displayText = value.text + ' (' + value.info + ')';
                        }

                        $(item).find('.inner-text').replaceWith(displayText);

                        $('#tasks').append(item);
                    });
                }
                ,
                error: function (xhr) {
                    alert('No Data');
                }
            });
        });

        $("#checkAll").click(function () {
            AllDone();
        });

        $("#deleteAll").click(function () {
            Purge();
        });

        $('.add-todo').on('keypress', function (e) {
            e.preventDefault
            if (e.which == 13) {
                if ($(this).val() != '') {
                    var todo = $(this).val();
                    createTodo(todo);
                } else {
                    // some validation
                }
            }
        });

        // mark task as done
        $('.todolist').on('change', '#tasks li input[type="checkbox"]', function () {
            if ($(this).prop('checked')) {
                var doneItem = $(this).parent().parent().find('label').text();
                $(this).parent().addClass('remove');
                done(doneItem);
            }
            else {

                var doneItem = $(this).parent().parent().find('label').text();
                $(this).parent().removeClass('remove');
                undone(doneItem);
            }
        });

        //delete done task
        $('.todolist').on('click', '.remove-item', function () {
            removeItem(this);
        });


        // TODO: Use a template for the line item markup
        $("#tasks li").on('dblclick', 'label', function () {
            if ($('#temp_enter').length === 0) {
                var original = $(this).text().trim();
                $(this).siblings().remove();
                $(this).replaceWith('<input id="temp_enter" type="text" class="form-control add-todo" value="' + original + '"></input>');

                $("#temp_enter").keyup(function (event) {
                    if (event.which == 13) {
                        var markup = '<li class="ui-state-default"><div class="checkbox"><label><input type="checkbox" value="" />' + $(this).val() + '</label> <button class="remove-item btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-trash"></span></button></div></li>';
                        $(this).parent().replaceWith(markup);

                    } else if (event.which == 27) {
                        var markup = '<li class="ui-state-default"><div class="checkbox"><label><input type="checkbox" value="" />' + original + '</label> <button class="remove-item btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-trash"></span></button></div></li>';
                        $(this).parent().replaceWith(markup);
                    }
                });

                $("#cancel_inline").click(function () {
                    var markup = '<li class="ui-state-default"><div class="checkbox"><label><input type="checkbox" value="" />' + original + '</label> <button class="remove-item btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-trash"></span></button></div></li>';
                    $(this).parent().replaceWith(markup);
                });
            }

        });

        //create task
        function createTodo(text) {

            var markup = '<li class="ui-state-default"><div class="checkbox"><label><input type="checkbox" value="" />' + text + '</label> <button class="remove-item btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-trash"></span></button></div></li>';
            $('#tasks').append(markup);

            $('.add-todo').val('');
        }

        //mark task as done
        function done(doneItem) {
            var done = doneItem;
        }

        //mark task as un-done
        function undone(doneItem) {
            var done = doneItem;
        }

        //mark all tasks as done
        function AllDone() {

            $('#tasks li > div > label').each(function () {

                $(this).addClass('remove');
                $(this).children('input').prop("checked", true);

            });

        }
        //remove done task from list
        function removeItem(element) {
            $(element).parent().remove();
        }

        function Purge() {
            $('#tasks li').remove();
        }

    </script>
}

Productivity.ToDo/Productivity.ToDo.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Productivity.ToDo.UI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Old School</a>
                <a asp-area="" asp-controller="CompositionDemo" asp-action="Index" class="navbar-brand">Composition</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">ToDo</a></li>*@
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>